# Generated by Django 4.1.7 on 2023-03-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.CharField(default="", max_length=50),
        ),
    ]
