# Generated by Django 4.1.7 on 2023-02-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
