# Generated by Django 4.1.7 on 2023-02-17 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_admin", "0002_userprofile_company_userprofile_job"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="is_admin",
            new_name="is_staff",
        ),
    ]
