# Generated by Django 4.1.7 on 2023-02-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_admin", "0003_rename_is_admin_userprofile_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="company",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="job",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
