# Generated by Django 4.1.7 on 2023-02-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_admin", "0004_userprofile_address_userprofile_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mobile",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
