# Generated by Django 4.1.7 on 2023-02-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_admin", "0005_userprofile_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
